version: '2'
services:
  payara:
    image: "airhacks/payara-micro"
    ports:
      - "8080:8080"
      - "5900:5900"
    environment:
       - ARCHIVE_NAME=target/PayaraDocker.war
    volumes:
       - ./target/PayaraDocker.war:/opt/target/PayaraDocker.war